# Work section

projects:
-  {name: Random Quote Machine, description: 'A random quote generator connected to multiple providers, allowing quotes to be shared via social media.'}
-  {name: Wikipedia Search, description: 'An implementation of Wikipedia search that uses its search API'}
-  {name: Twitch.tv Status, description: 'An app that monitors the status of Twitch.tv streamers'}
-  {name: Camper Leaderboard, description: 'Find out who has the most brownie points on FreeCodeCamp over the past 30 days or all time'}
-  {name: Pomodoro Timer, description: 'Meaning tomato in Italian, the Pomodoro method involves working for a specific amount of time with scheduled breaks'}
-  {name: Calculator, description: 'A JavaScript powered calculator'}

skills:
-  {name: HTML}
-  {name: CSS}
-  {name: JavaScript}
-  {name: Bootstrap}
-  {name: Jquery}
-  {name: Jekyll}
-  {name: Sass}
-  {name: React}
-  {name: Webpack}
-  {name: Git}
-  {name: Wordpress}
-  {name: D3}
